cc_binary(
        name = "Weather-Station",
        srcs = [
            "Subject.h",
            "Observer.h",
            "DisplayElement.h",
            "WeatherData.h",
            "WeatherData.cpp",
            "CurrentConditionDisplay.h",
            "CurrentConditionDisplay.cpp",
            "StatisticsDisplay.h",
            "StatisticsDisplay.cpp",
            "ForcastDisplay.h",
            "ForcastDisplay.cpp",
            "WeatherStation.cpp"
        ]
)